name: Campify CI/CD Pipeline

on:
  push:
    branches: [ "Marya" ]
  pull_request:
    branches: [ "Marya" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379
      mongodb:
        image: mongo
        ports:
          - 27017:27017

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Install Dependencies
      run: |
          cd server
          npm install

    - name: Syntax Check (Linter substitute)
      run: |
          cd server
          node --check src/app.js
          node --check workers/emailWorker.js
          echo "✅ Kod analizi başarıyla tamamlandı!"


    - name: Build Success Message
      run: echo "🚀 CI/CD Süreci Başarıyla Tamamlandı!"